---

- name: mkdir neovim
  file:
    state: directory
    path: "{{ item }}"
    recurse: "yes"
  loop:
    - "~/.local/share/nvim/site/autoload"
    - "~/.config/nvim/"

- name: packer is installed
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim

- name: configuration files are linked
  file:
    state: link
    force: yes
    src: "{{ role_path }}/files/{{ item }}"
    path: "~/.config/nvim/{{ item }}"
  loop:
    - "init.lua"
    - "legacy.vim"
  register: configuration_result

- name: node dependencies installed
  become: "yes"
  zypper:
    name: "{{ item }}"
  loop:
    - nodejs
    - npm

- name: python neovim bindings installed
  become: "yes"
  zypper:
    name: "{{ item }}"
  loop:
    - python3-neovim
